// Generated by CoffeeScript 1.9.3
(function() {
  var drawing_demo, drawing_demo_p5;

  drawing_demo = function(p_o) {
    var amplitude, calcWave, dy, h, period, renderWave, theta, xvalues, yspacing;
    yspacing = 10;
    h = 0;
    theta = 0.0;
    amplitude = 75.0;
    period = 500.0;
    dy = 0;
    xvalues = [];
    calcWave = function() {
      var i, j, ref, results, y;
      theta += 0.02;
      y = theta;
      results = [];
      for (i = j = 0, ref = xvalues.length; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
        xvalues[i] = p_o.sin(y) * amplitude;
        results.push(y += dy);
      }
      return results;
    };
    renderWave = function() {
      var j, len, ref, results, y;
      p_o.stroke(30, 30, 30);
      ref = xvalues.slice(0, +(xvalues.length - 1) + 1 || 9e9);
      results = [];
      for (j = 0, len = ref.length; j < len; j += 2) {
        y = ref[j];
        results.push(p_o.line(xvalues[y], y * yspacing, xvalues[y + 1], (y + 1) * yspacing));
      }
      return results;
    };
    p_o.setup = function() {
      var canvas, canvasDiv, height, width;
      canvasDiv = document.getElementById('drawing-box');
      width = canvasDiv.offsetWidth;
      height = canvasDiv.offsetHeight;
      canvas = p_o.createCanvas(width, height);
      canvas.parent('drawing-canvas');
      dy = (p_o.TWO_PI / period) * yspacing;
      h = height + 16;
      xvalues = new Array(p_o.floor(h / yspacing));
      return p_o.background(255);
    };
    return p_o.draw = function() {
      p_o.background(255);
      calcWave();
      return renderWave();
    };
  };

  drawing_demo_p5 = new p5(drawing_demo, "drawing-canvas");

}).call(this);
